server:
  port: 8090


spring:
  application:
    name: cooky-rbac
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/cooky-cloud-rbac?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    hikari:
      pool-name: cooky-rbac-pool
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
security:
  oauth2:
    resource:
      id: cooku-rbac
      user-info-uri: http://localhost:10000/auth/user
#      prefer-token-info: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yuuki.cooky.rbac.model.entity

